using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

// iFuse for Windows: exposes the iOS AFC media directory through Dokan 2.
internal static class Program
{
    const int OK=0, NOT_IMPL=unchecked((int)0xC0000002), ACCESS=unchecked((int)0xC0000022), NOT_FOUND=unchecked((int)0xC0000034), PATH_NOT_FOUND=unchecked((int)0xC000003A), EXISTS=unchecked((int)0xC0000035), NOT_DIR=unchecked((int)0xC0000103), IS_DIR=unchecked((int)0xC00000BA), DIR_NOT_EMPTY=unchecked((int)0xC0000101), IO_ERROR=unchecked((int)0xC0000185), DISK_FULL=unchecked((int)0xC000007F);
    const uint DIR_ATTR=0x10, NORMAL_ATTR=0x80, FILE_DIRECTORY_FILE=1;
    static IntPtr device, afc, houseArrest;
    static string RootPrefix = Environment.GetEnvironmentVariable("IFUSE_ROOT_PATH") ?? "";
    static readonly object Gate = new object();
    static readonly List<Delegate> KeepAlive = new List<Delegate>();

    [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] struct DokanOptions { public ushort Version; public byte SingleThread; public uint Options; public ulong GlobalContext; public string MountPoint; public string UNCName; public uint Timeout, AllocationUnitSize, SectorSize, VolumeSecurityDescriptorLength; [MarshalAs(UnmanagedType.ByValArray, SizeConst=1024)] public byte[] VolumeSecurityDescriptor; }
    [StructLayout(LayoutKind.Sequential)] struct DokanFileInfo { public ulong Context,DokanContext; public IntPtr DokanOptions,ProcessingContext; public uint ProcessId; public byte IsDirectory,DeletePending,PagingIo,SynchronousIo,Nocache,WriteToEndOfFile; }
    [StructLayout(LayoutKind.Sequential)] struct FileTime { public uint Low, High; }
    [StructLayout(LayoutKind.Sequential)] struct ByHandleInfo { public uint Attributes; public FileTime Creation,Access,Write; public uint VolumeSerial,SizeHigh,SizeLow,Links,IndexHigh,IndexLow; }
    [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Unicode)] struct FindData { public uint Attributes; public FileTime Creation,Access,Write; public uint SizeHigh,SizeLow,Reserved0,Reserved1; [MarshalAs(UnmanagedType.ByValTStr, SizeConst=260)] public string FileName; [MarshalAs(UnmanagedType.ByValTStr, SizeConst=14)] public string Alternate; }
    [StructLayout(LayoutKind.Sequential)] struct Ops { public IntPtr Create,Cleanup,Close,Read,Write,Flush,Info,Find,FindPattern,SetAttrs,SetTime,DeleteFile,DeleteDir,Move,SetEnd,SetAllocation,Lock,Unlock,Space,Volume,Mounted,Unmounted,GetSecurity,SetSecurity,FindStreams; }

    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int CreateCb(string p,IntPtr sec,uint access,uint attrs,uint share,uint disposition,uint options,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate void VoidCb(string p,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int IoCb(string p,IntPtr buf,uint len,IntPtr done,long off,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int PathCb(string p,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int InfoCb(string p,IntPtr buf,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int FillCb(ref FindData data,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int FindCb(string p,IntPtr fill,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int AttrCb(string p,uint attrs,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int TimeCb(string p,IntPtr c,IntPtr a,IntPtr w,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int MoveCb(string p,string n,int replace,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int SizeCb(string p,long size,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)] delegate int SpaceCb(IntPtr avail,IntPtr total,IntPtr free,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int VolumeCb(IntPtr name,uint nameN,IntPtr serial,IntPtr max,IntPtr flags,IntPtr fs,uint fsN,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi, CharSet=CharSet.Unicode)] delegate int MountedCb(string p,ref DokanFileInfo fi);
    [UnmanagedFunctionPointer(CallingConvention.Winapi)] delegate int UnmountedCb(ref DokanFileInfo fi);

    [DllImport("dokan2.dll",CallingConvention=CallingConvention.Winapi)] static extern int DokanMain(ref DokanOptions options,ref Ops operations);
    [DllImport("dokan2.dll",CallingConvention=CallingConvention.Winapi)] static extern void DokanInit();
    [DllImport("dokan2.dll",CallingConvention=CallingConvention.Winapi)] static extern void DokanShutdown();
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int idevice_new_with_options(out IntPtr d,string udid,int options);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void idevice_free(IntPtr d);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int lockdownd_client_new_with_handshake(IntPtr d,out IntPtr c,string label);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int lockdownd_start_service(IntPtr c,string name,out IntPtr svc);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void lockdownd_client_free(IntPtr c);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void lockdownd_service_descriptor_free(IntPtr svc);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_client_new(IntPtr d,IntPtr svc,out IntPtr c);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int house_arrest_client_new(IntPtr d,IntPtr svc,out IntPtr c);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int house_arrest_send_command(IntPtr c,string command,string appid);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int house_arrest_get_result(IntPtr c,out IntPtr result);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int house_arrest_client_free(IntPtr c);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_client_new_from_house_arrest_client(IntPtr h,out IntPtr c);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void plist_free(IntPtr p);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int instproxy_client_start_service(IntPtr d,out IntPtr c,string label);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int instproxy_browse(IntPtr c,IntPtr options,out IntPtr apps);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int instproxy_client_free(IntPtr c);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern uint plist_array_get_size(IntPtr p);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern IntPtr plist_array_get_item(IntPtr p,uint n);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern IntPtr plist_dict_get_item(IntPtr p,string key);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void plist_get_bool_val(IntPtr p,out byte value);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void plist_get_string_val(IntPtr p,out IntPtr value);
    [DllImport("libplist-2.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void plist_mem_free(IntPtr p);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_client_free(IntPtr c);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_get_file_info(IntPtr c,string p,out IntPtr info);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_get_device_info(IntPtr c,out IntPtr info);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern void afc_dictionary_free(IntPtr info);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_read_directory(IntPtr c,string p,out IntPtr list);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_file_open(IntPtr c,string p,int mode,out ulong h);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_file_close(IntPtr c,ulong h);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_file_seek(IntPtr c,ulong h,long off,int whence);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_file_read(IntPtr c,ulong h,IntPtr data,uint len,out uint read);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_file_write(IntPtr c,ulong h,IntPtr data,uint len,out uint written);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_make_directory(IntPtr c,string p);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_remove_path(IntPtr c,string p);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_rename_path(IntPtr c,string p,string n);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_truncate(IntPtr c,string p,ulong size);
    [DllImport("libimobiledevice-1.0.dll",CallingConvention=CallingConvention.Cdecl)] static extern int afc_set_file_time(IntPtr c,string p,ulong ns);

    static string P(string p) { return RootPrefix + p.Replace('\\','/'); }
    static Dictionary<string,string> Dict(IntPtr pp) { var d=new Dictionary<string,string>(); if(pp==IntPtr.Zero)return d; for(int i=0;;i+=2){var k=Marshal.ReadIntPtr(pp,i*IntPtr.Size); if(k==IntPtr.Zero)break; var v=Marshal.ReadIntPtr(pp,(i+1)*IntPtr.Size); d[Marshal.PtrToStringAnsi(k)??""]=Marshal.PtrToStringAnsi(v)??"";} return d; }
    static int Status(int e){ if(e==0)return OK; switch(e){case 8:return NOT_FOUND;case 9:return IS_DIR;case 10:return DIR_NOT_EMPTY;case 11:return ACCESS;case 16:return EXISTS;case 18:return DISK_FULL;default:return IO_ERROR;} }
    static bool Stat(string p,out Dictionary<string,string> d){lock(Gate){IntPtr x;int e=afc_get_file_info(afc,P(p),out x);if(e!=0&&p=="/"&&RootPrefix.Length>0){afc_make_directory(afc,RootPrefix);e=afc_get_file_info(afc,P(p),out x);}d=Dict(x);if(x!=IntPtr.Zero)afc_dictionary_free(x);return e==0;}}
    static bool IsDir(Dictionary<string,string>d){string t;return d.TryGetValue("st_ifmt",out t)&&t=="S_IFDIR";}
    static ulong U(Dictionary<string,string>d,string k){string s;ulong n;return d.TryGetValue(k,out s)&&ulong.TryParse(s,out n)?n:0;}
    static FileTime FT(ulong ns){long ticks=unchecked((long)(ns/100))+116444736000000000L;return new FileTime{Low=(uint)ticks,High=(uint)(ticks>>32)};}
    static FindData Data(string name,Dictionary<string,string>d){ulong n=U(d,"st_size");var t=FT(U(d,"st_mtime"));return new FindData{FileName=name,Alternate="",Attributes=IsDir(d)?DIR_ATTR:NORMAL_ATTR,Creation=t,Access=t,Write=t,SizeHigh=(uint)(n>>32),SizeLow=(uint)n};}
    static IntPtr Fn(Delegate d){KeepAlive.Add(d);return Marshal.GetFunctionPointerForDelegate(d);}
    static string PlistString(IntPtr node){if(node==IntPtr.Zero)return "";IntPtr s;plist_get_string_val(node,out s);if(s==IntPtr.Zero)return "";string value=Marshal.PtrToStringAnsi(s)??"";plist_mem_free(s);return value;}
    static int ListApps(string udid,bool network){IntPtr d=IntPtr.Zero,ip=IntPtr.Zero,apps=IntPtr.Zero;try{int e=idevice_new_with_options(out d,udid,network?2:1);if(e!=0)throw new Exception("No iPhone found (error "+e+").");e=instproxy_client_start_service(d,out ip,"ifuse-win");if(e!=0)throw new Exception("Could not start installation proxy (error "+e+").");e=instproxy_browse(ip,IntPtr.Zero,out apps);if(e!=0||apps==IntPtr.Zero)throw new Exception("Could not retrieve installed apps (error "+e+").");Console.WriteLine("BundleId\tName");uint count=plist_array_get_size(apps);for(uint i=0;i<count;i++){IntPtr app=plist_array_get_item(apps,i),share=plist_dict_get_item(app,"UIFileSharingEnabled");byte enabled=0;if(share!=IntPtr.Zero)plist_get_bool_val(share,out enabled);if(enabled!=0){string id=PlistString(plist_dict_get_item(app,"CFBundleIdentifier"));string name=PlistString(plist_dict_get_item(app,"CFBundleDisplayName"));if(name.Length==0)name=PlistString(plist_dict_get_item(app,"CFBundleName"));if(id.Length>0)Console.WriteLine(id+"\t"+name);}}return 0;}catch(Exception ex){Console.Error.WriteLine("ifuse-win: "+ex.Message);return 1;}finally{if(apps!=IntPtr.Zero)plist_free(apps);if(ip!=IntPtr.Zero)instproxy_client_free(ip);if(d!=IntPtr.Zero)idevice_free(d);}}

    static int Create(string p,IntPtr s,uint access,uint attrs,uint share,uint disp,uint options,ref DokanFileInfo fi){try{Dictionary<string,string>d;bool exists=Stat(p,out d),wantDir=(options&FILE_DIRECTORY_FILE)!=0;if(exists&&IsDir(d)){if(disp==2)return EXISTS;fi.IsDirectory=1;return OK;}if(wantDir){if(exists)return NOT_DIR;if(disp==1||disp==4)return PATH_NOT_FOUND;lock(Gate){int e=afc_make_directory(afc,P(p));if(e!=0)return Status(e);}fi.IsDirectory=1;return OK;}if(!exists&&(disp==1||disp==4))return NOT_FOUND;if(exists&&disp==2)return EXISTS;int mode=(disp==0||disp==4||disp==5)?4:2;lock(Gate){ulong h;int e=afc_file_open(afc,P(p),mode,out h);if(e!=0)return Status(e);fi.Context=h;}return exists&&(disp==3||disp==5)?EXISTS:OK;}catch(Exception ex){Console.Error.WriteLine("CreateFile "+p+": "+ex.Message);return IO_ERROR;}}
    static void Cleanup(string p,ref DokanFileInfo fi){lock(Gate){if(fi.Context!=0){afc_file_close(afc,fi.Context);fi.Context=0;}if(fi.DeletePending!=0)afc_remove_path(afc,P(p));}}
    static void Close(string p,ref DokanFileInfo fi){lock(Gate){if(fi.Context!=0){afc_file_close(afc,fi.Context);fi.Context=0;}}}
    static int Read(string p,IntPtr b,uint n,IntPtr done,long off,ref DokanFileInfo fi){lock(Gate){ulong h=fi.Context;bool temp=h==0;if(temp&&afc_file_open(afc,P(p),1,out h)!=0)return NOT_FOUND;uint got=0;int e=afc_file_seek(afc,h,off,0);if(e==0)e=afc_file_read(afc,h,b,n,out got);Marshal.WriteInt32(done,(int)got);if(temp)afc_file_close(afc,h);return Status(e);}}
    static int Write(string p,IntPtr b,uint n,IntPtr done,long off,ref DokanFileInfo fi){lock(Gate){ulong h=fi.Context;bool temp=h==0;if(temp&&afc_file_open(afc,P(p),2,out h)!=0)return NOT_FOUND;uint put=0;int e=afc_file_seek(afc,h,off,0);if(e==0)e=afc_file_write(afc,h,b,n,out put);Marshal.WriteInt32(done,(int)put);if(temp)afc_file_close(afc,h);return Status(e);}}
    static int Info(string p,IntPtr b,ref DokanFileInfo fi){Dictionary<string,string>d;if(!Stat(p,out d))return NOT_FOUND;ulong n=U(d,"st_size");var t=FT(U(d,"st_mtime"));var x=new ByHandleInfo{Attributes=IsDir(d)?DIR_ATTR:NORMAL_ATTR,Creation=t,Access=t,Write=t,SizeHigh=(uint)(n>>32),SizeLow=(uint)n,Links=1,IndexLow=(uint)P(p).GetHashCode()};Marshal.StructureToPtr(x,b,false);return OK;}
    static int Find(string p,IntPtr f,ref DokanFileInfo fi){var fill=(FillCb)Marshal.GetDelegateForFunctionPointer(f,typeof(FillCb));lock(Gate){IntPtr list;int e=afc_read_directory(afc,P(p),out list);if(e!=0)return Status(e);try{for(int i=0;;i++){IntPtr q=Marshal.ReadIntPtr(list,i*IntPtr.Size);if(q==IntPtr.Zero)break;string name=Marshal.PtrToStringAnsi(q);Dictionary<string,string>d;if(Stat(p.TrimEnd('\\','/')+"/"+name,out d)){var fd=Data(name,d);fill(ref fd,ref fi);}}}finally{afc_dictionary_free(list);}return OK;}}
    static int SetTime(string p,IntPtr c,IntPtr a,IntPtr w,ref DokanFileInfo fi){if(w==IntPtr.Zero)return OK;var t=(FileTime)Marshal.PtrToStructure(w,typeof(FileTime));ulong ticks=((ulong)t.High<<32)|t.Low;ulong ns=ticks>116444736000000000UL?(ticks-116444736000000000UL)*100:0;lock(Gate)return Status(afc_set_file_time(afc,P(p),ns));}
    static int Delete(string p,ref DokanFileInfo fi){Dictionary<string,string>d;return Stat(p,out d)?OK:NOT_FOUND;}
    static int DeleteDir(string p,ref DokanFileInfo fi){lock(Gate){IntPtr list;int e=afc_read_directory(afc,P(p),out list);if(e!=0)return Status(e);int count=0;while(Marshal.ReadIntPtr(list,count*IntPtr.Size)!=IntPtr.Zero)count++;afc_dictionary_free(list);return count>2?DIR_NOT_EMPTY:OK;}}
    static int Move(string p,string n,int replace,ref DokanFileInfo fi){lock(Gate){Dictionary<string,string>d;if(Stat(n,out d)){if(replace==0)return EXISTS;afc_remove_path(afc,P(n));}return Status(afc_rename_path(afc,P(p),P(n)));}}
    static int Resize(string p,long n,ref DokanFileInfo fi){if(n<0)return IO_ERROR;lock(Gate)return Status(afc_truncate(afc,P(p),(ulong)n));}
    static int Space(IntPtr a,IntPtr t,IntPtr f,ref DokanFileInfo fi){lock(Gate){IntPtr x;int e=afc_get_device_info(afc,out x);var d=Dict(x);if(x!=IntPtr.Zero)afc_dictionary_free(x);ulong total=U(d,"FSTotalBytes"),free=U(d,"FSFreeBytes");Marshal.WriteInt64(a,(long)free);Marshal.WriteInt64(t,(long)total);Marshal.WriteInt64(f,(long)free);return Status(e);}}
    static int Volume(IntPtr n,uint nn,IntPtr serial,IntPtr max,IntPtr flags,IntPtr fs,uint fsn,ref DokanFileInfo fi){WriteWide(n,nn,"iPhone");WriteWide(fs,fsn,"AFC");Marshal.WriteInt32(serial,0x69464F4E);Marshal.WriteInt32(max,255);Marshal.WriteInt32(flags,2|4);return OK;}
    static void WriteWide(IntPtr p,uint chars,string s){byte[] b=Encoding.Unicode.GetBytes(s+"\0");Marshal.Copy(b,0,p,Math.Min(b.Length,(int)chars*2));}

    static Ops BuildOps(){return new Ops{Create=Fn(new CreateCb(Create)),Cleanup=Fn(new VoidCb(Cleanup)),Close=Fn(new VoidCb(Close)),Read=Fn(new IoCb(Read)),Write=Fn(new IoCb(Write)),Flush=Fn(new PathCb((string p,ref DokanFileInfo f)=>OK)),Info=Fn(new InfoCb(Info)),Find=Fn(new FindCb(Find)),SetAttrs=Fn(new AttrCb((string p,uint a,ref DokanFileInfo f)=>OK)),SetTime=Fn(new TimeCb(SetTime)),DeleteFile=Fn(new PathCb(Delete)),DeleteDir=Fn(new PathCb(DeleteDir)),Move=Fn(new MoveCb(Move)),SetEnd=Fn(new SizeCb(Resize)),SetAllocation=Fn(new SizeCb(Resize)),Space=Fn(new SpaceCb(Space)),Volume=Fn(new VolumeCb(Volume)),Mounted=Fn(new MountedCb((string p,ref DokanFileInfo f)=>{Console.WriteLine("Mounted iPhone at "+p+" (Ctrl+C to unmount)");return OK;})),Unmounted=Fn(new UnmountedCb((ref DokanFileInfo f)=>{Console.WriteLine("Unmounted");return OK;}))};}
    static int Main(string[] args){string mount="M:\\",udid=null,documents=null;bool network=false,debug=false,list=false;for(int i=0;i<args.Length;i++){switch(args[i]){case "--udid":if(++i<args.Length)udid=args[i];break;case "--documents":if(++i<args.Length)documents=args[i];break;case "--list-apps":list=true;break;case "--network":network=true;break;case "--debug":debug=true;break;case "--help":case "-h":Help();return 0;default:mount=args[i];break;}}if(list)return ListApps(udid,network);bool driveMount=mount.Length==2&&mount[1]==':';if(driveMount)mount+="\\";else{mount=System.IO.Path.GetFullPath(mount);if(!System.IO.Directory.Exists(mount)){Console.Error.WriteLine("Mount folder does not exist: "+mount);return 2;}}IntPtr ld=IntPtr.Zero,svc=IntPtr.Zero;bool dokanStarted=false;try{int e=idevice_new_with_options(out device,udid,network?2:1);if(e!=0)throw new Exception("No iPhone found (error "+e+"). Unlock it, tap Trust, and check the Apple USB driver.");e=lockdownd_client_new_with_handshake(device,out ld,"ifuse-win");if(e!=0)throw new Exception("Pairing/lockdown failed (error "+e+"). Unlock the iPhone and tap Trust.");string service=documents==null?"com.apple.afc":"com.apple.mobile.house_arrest";e=lockdownd_start_service(ld,service,out svc);if(e!=0)throw new Exception("Could not start "+service+" (error "+e+").");if(documents==null){e=afc_client_new(device,svc,out afc);}else{e=house_arrest_client_new(device,svc,out houseArrest);if(e==0)e=house_arrest_send_command(houseArrest,"VendDocuments",documents);IntPtr reply=IntPtr.Zero;if(e==0)e=house_arrest_get_result(houseArrest,out reply);if(reply!=IntPtr.Zero)plist_free(reply);if(e==0)e=afc_client_new_from_house_arrest_client(houseArrest,out afc);if(e==0)RootPrefix="/Documents";}if(e!=0||afc==IntPtr.Zero)throw new Exception(documents==null?"Could not connect to AFC (error "+e+").":"Could not access Documents for '"+documents+"' (error "+e+"). The app must support iTunes/File Sharing.");var o=new DokanOptions{Version=231,Options=(uint)((driveMount?0x40:0)|(debug?1:0)),MountPoint=mount,Timeout=60000,AllocationUnitSize=4096,SectorSize=4096,VolumeSecurityDescriptor=new byte[1024]};var ops=BuildOps();Console.WriteLine("Connecting "+(documents==null?"iPhone AFC media storage":documents+" Documents")+" to "+mount);DokanInit();dokanStarted=true;int result=DokanMain(ref o,ref ops);if(result!=0)Console.Error.WriteLine("Dokan mount failed with code "+result+".");return result;}catch(Exception ex){Console.Error.WriteLine("ifuse-win: "+(debug?ex.ToString():ex.Message));return 1;}finally{if(dokanStarted)DokanShutdown();if(afc!=IntPtr.Zero)afc_client_free(afc);if(houseArrest!=IntPtr.Zero)house_arrest_client_free(houseArrest);if(svc!=IntPtr.Zero)lockdownd_service_descriptor_free(svc);if(ld!=IntPtr.Zero)lockdownd_client_free(ld);if(device!=IntPtr.Zero)idevice_free(device);}}
    static void Help(){Console.WriteLine("iFuse for Windows (Dokan/AFC)\n\nUsage: ifuse-win.exe [drive-or-folder] [--documents BUNDLE_ID] [--udid ID] [--network] [--debug]\n       ifuse-win.exe --list-apps\n\nMedia: .\\ifuse-win.exe M:\nVLC:   .\\ifuse-win.exe M: --documents org.videolan.vlc-ios");}
}
